# -*- coding: utf-8 -*-
"""AI_Resume_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iOBI12TpxUy7rX4vzgctAqE4ziw383y
"""

#pip install streamlit pandas numpy scikit-learn nltk spacy pdfplumber

pip install transformers sentence-transformers

!pip install pdfplumber nltk scikit-learn pandas

import pdfplumber
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer
import streamlit as st
import pdfplumber

resume_path = "Iswarya Resume.pdf"

def extract_text(pdf_file):
    text = ""

    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            text += page.extract_text()

    return text

resume_text = extract_text(resume_path)

print(resume_text)

skills_db = [
    "python",
    "machine learning",
    "deep learning",
    "sql",
    "tensorflow",
    "data analysis",
    "nlp"
]

def extract_skills(text):

    found_skills = []

    text = text.lower()

    for skill in skills_db:
        if skill in text:
            found_skills.append(skill)

    return found_skills

skills = extract_skills(resume_text)

print("Skills Found:", skills)

def ats_score(skills):

    total_skills = len(skills_db)

    score = (len(skills) / total_skills) * 100

    return round(score, 2)

score = ats_score(skills)

print("ATS Score:", score)

job_description = """
Looking for a candidate with Python, Machine Learning, NLP and Deep Learning skills.
"""

def match_percentage(resume, jd):

    text = [resume, jd]

    cv = CountVectorizer()

    matrix = cv.fit_transform(text)

    similarity = (
        matrix * matrix.T
    ).toarray()[0][1]

    return round(similarity * 100, 2)

match = match_percentage(resume_text, job_description)

print("Job Match Percentage:", match)

questions = {
    "python": "Explain Python decorators.",
    "machine learning": "What is overfitting?",
    "sql": "What is normalization?",
    "nlp": "What is tokenization?"
}

print("\nInterview Questions:\n")

for skill in skills:
    if skill in questions:
        print("-", questions[skill])

print("======== RESUME ANALYSIS REPORT ========")

print("Skills:", skills)

print("ATS Score:", score)

print("Job Match:", match)

print("========================================")

import matplotlib.pyplot as plt

labels = ['Matched', 'Missing']
values = [len(skills), len(skills_db)-len(skills)]

plt.pie(values, labels=labels, autopct='%1.1f%%')
plt.title("Skill Analysis")
plt.show()

